### ISSUE TITLE
Enable additional auth methods for bq connections

### ISSUE THREAD

**Issue by mary-hallewell** [transform-data/metricflow#53]
**Describe the Feature**
Allow users to authorize with user account json credentials or oauth as opposed to solely supporting service account credential file authorization 

**Would you like to contribute?**
Potentially (definitely would be happy to help with testing and gathering requirements but not sure I have the bandwidth to write the pr myself)

**Anything Else?**
Currently the errors you get when you try and use a user json credential file is complaining about various required fields not being present in the file. Also it's not really intuitive to have the field for the credential file location in the config.yml file be called `dwh_password`. The comment after clarifies but the name is not useful for new adopters.

**Comment by tlento** [comment]
Thanks for this! 

I think we need broader discussion around oauth, but standard user credential support (as opposed to service user logins) seems like something we should add. It is already available for Snowflake and Redshift, I think the only reason it didn't happen for BigQuery is because they're the only ones with the JSON credential format.

@WilliamDee I've got a couple of tactical questions for you that I'll check in on offline but in the meantime if you think this is a good first issue please add the label.

**Comment by WilliamDee** [comment]
https://github.com/transform-data/metricflow/pull/62 This PR addresses the concern over the `dwh_password` confusion as well as supporting a way to authenticate via an end user

**Comment by WilliamDee** [comment]
Done in #62
